using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;
[InitializeOnLoad]
public static class NecroFantasyImportProbe {
 const string Job="Library/fantasy-import-job.txt", Root="Artifacts/FantasyImport-20261011", Out="docs/evidence/FantasyEquipment-20261011";
 [Serializable] public class Row { public string Package,Path,Guid,Disposition; }
 [Serializable] public class Manifest { public Row[] rows; }
 static NecroFantasyImportProbe(){Log("helper-loaded.txt","VERSION2 readback/exclusion support Unity"+Application.unityVersion);EditorApplication.update+=Tick;Application.logMessageReceived+=OnLog;AssetDatabase.importPackageCompleted+=s=>{if(SessionState.GetString("FantasyImport.Pending","")!="")Log("events.txt","Native importPackageCompleted "+s);};AssetDatabase.importPackageFailed+=(p,e)=>{SessionState.SetBool("FantasyImport.Error",true);Log("errors.txt",p+" "+e);};}
 static void Log(string f,string s){Directory.CreateDirectory(Out);File.AppendAllText(Out+"/"+f,DateTimeOffset.Now.ToString("o")+" "+s+"\n");}
 static void OnLog(string c,string st,LogType t){if(SessionState.GetString("FantasyImport.Pending","")!=""&&(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)){SessionState.SetBool("FantasyImport.Error",true);Log("errors.txt",t+" "+c+"\n"+st);}}
 static void Tick(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||EditorApplication.isPlayingOrWillChangePlaymode)return;
  var pending=SessionState.GetString("FantasyImport.Pending","");if(pending!="") {if(EditorApplication.timeSinceStartup<SessionState.GetFloat("FantasyImport.Wait",0))return;try{if(SessionState.GetBool("FantasyImport.Error",false))throw new Exception("Native import error; stop, preserve project");var m=JsonUtility.FromJson<Manifest>(File.ReadAllText(Root+"/manifest-"+pending+".json"));foreach(var r in m.rows){if(r.Disposition.StartsWith("EXCLUDED"))continue;if(!File.Exists(r.Path)&&!Directory.Exists(r.Path))throw new Exception("Missing "+r.Path);if(AssetDatabase.AssetPathToGUID(r.Path)!=r.Guid)throw new Exception("GUID mismatch "+r.Path);}Log("imports.txt","PASS native asset readback "+pending+" paths="+m.rows.Length);File.WriteAllText(Root+"/done-"+pending+".txt","PASS");}catch(Exception e){Log("failure.txt",e.ToString());File.WriteAllText(Root+"/done-"+pending+".txt","FAIL "+e.Message);}finally{SessionState.SetString("FantasyImport.Pending","");}return;}
  if(!File.Exists(Job))return;var cmd=File.ReadAllText(Job).Trim();File.Delete(Job);try{if(cmd=="INVENTORY"){Inventory();return;}int ix;if(cmd.StartsWith("READBACK:")){ix=int.Parse(cmd.Substring(9));SessionState.SetBool("FantasyImport.Error",false);SessionState.SetString("FantasyImport.Pending",ix.ToString());SessionState.SetFloat("FantasyImport.Wait",(float)EditorApplication.timeSinceStartup+1);Log("imports.txt","REVALIDATE after isolated optional sample scripts "+ix);return;}if(!int.TryParse(cmd,out ix)||ix<0||ix>6)throw new Exception("Invalid import index");if(UnityEditor.SceneManagement.EditorSceneManager.sceneCount!=1||SceneManager.GetActiveScene().isDirty)throw new Exception("Protect dirty scene");var m=JsonUtility.FromJson<Manifest>(File.ReadAllText(Root+"/manifest-"+ix+".json"));var path=Root+"/filtered/"+m.rows[0].Package;if(!File.Exists(path))throw new Exception("Missing filtered package");SessionState.SetBool("FantasyImport.Error",false);SessionState.SetString("FantasyImport.Pending",ix.ToString());SessionState.SetFloat("FantasyImport.Wait",(float)EditorApplication.timeSinceStartup+8);Log("imports.txt","START "+ix+" "+path);AssetDatabase.ImportPackage(path,false);}catch(Exception e){SessionState.SetString("FantasyImport.Pending","");Log("failure.txt",e.ToString());}}
 static void Inventory(){foreach(var name in new[]{"PolygonGoblinWarCamp","PolygonVikingRealm","AnimationGoblinLocomotion","SidekickGoblinFighters","PolygonNatureBiomes","PolygonParticleFX","SimplePropsItemsIcons"}){var paths=AssetDatabase.GetAllAssetPaths().Where(p=>p.StartsWith("Assets/Synty/")&&p.IndexOf(name,StringComparison.OrdinalIgnoreCase)>=0).ToArray();Log("inventory.txt",name+" paths="+paths.Length);}
  foreach(var path in AssetDatabase.FindAssets("t:AnimationClip",new[]{"Assets/Synty"}).Select(AssetDatabase.GUIDToAssetPath).Distinct())foreach(var c in AssetDatabase.LoadAllAssetsAtPath(path).OfType<AnimationClip>().Where(c=>!c.name.StartsWith("__preview__")))Log("clips.txt",path+" | "+c.name+" human="+c.isHumanMotion+" length="+c.length);
  foreach(var path in AssetDatabase.FindAssets("t:Prefab",new[]{"Assets/Synty"}).Select(AssetDatabase.GUIDToAssetPath).Where(p=>System.Text.RegularExpressions.Regex.IsMatch(p,"Dagger|Wand|Staff|Weapon|Axe",System.Text.RegularExpressions.RegexOptions.IgnoreCase)))Log("weapons.txt",path);
  Log("inventory.txt","AssetDatabase inventory completed; render/material/motion quality not inferred");}
}
